"""
ticker_list.py
--------------
Static autocomplete options for the portfolio ticker input.
Covers S&P 500 + NASDAQ 100 major components (~350 tickers).

Format: [{"value": "AAPL", "label": "AAPL — Apple Inc."}, ...]
"""

_TICKERS: list[tuple[str, str]] = [
    # ── Technology ─────────────────────────────────────────────────────────────
    ("AAPL",  "Apple Inc."),
    ("MSFT",  "Microsoft Corp."),
    ("NVDA",  "NVIDIA Corp."),
    ("GOOGL", "Alphabet Inc. (Class A)"),
    ("GOOG",  "Alphabet Inc. (Class C)"),
    ("META",  "Meta Platforms Inc."),
    ("AMZN",  "Amazon.com Inc."),
    ("TSLA",  "Tesla Inc."),
    ("AVGO",  "Broadcom Inc."),
    ("ORCL",  "Oracle Corp."),
    ("AMD",   "Advanced Micro Devices Inc."),
    ("INTC",  "Intel Corp."),
    ("QCOM",  "Qualcomm Inc."),
    ("TXN",   "Texas Instruments Inc."),
    ("CRM",   "Salesforce Inc."),
    ("ADBE",  "Adobe Inc."),
    ("NOW",   "ServiceNow Inc."),
    ("INTU",  "Intuit Inc."),
    ("NFLX",  "Netflix Inc."),
    ("CSCO",  "Cisco Systems Inc."),
    ("IBM",   "International Business Machines Corp."),
    ("HPQ",   "HP Inc."),
    ("HPE",   "Hewlett Packard Enterprise Co."),
    ("DELL",  "Dell Technologies Inc."),
    ("MU",    "Micron Technology Inc."),
    ("AMAT",  "Applied Materials Inc."),
    ("LRCX",  "Lam Research Corp."),
    ("KLAC",  "KLA Corp."),
    ("MRVL",  "Marvell Technology Inc."),
    ("FTNT",  "Fortinet Inc."),
    ("PANW",  "Palo Alto Networks Inc."),
    ("SNPS",  "Synopsys Inc."),
    ("CDNS",  "Cadence Design Systems Inc."),
    ("ANSS",  "ANSYS Inc."),
    ("PLTR",  "Palantir Technologies Inc."),
    ("SNOW",  "Snowflake Inc."),
    ("DDOG",  "Datadog Inc."),
    ("CRWD",  "CrowdStrike Holdings Inc."),
    ("ZS",    "Zscaler Inc."),
    ("NET",   "Cloudflare Inc."),
    ("OKTA",  "Okta Inc."),
    ("TWLO",  "Twilio Inc."),
    ("MDB",   "MongoDB Inc."),
    ("TEAM",  "Atlassian Corp."),
    ("WDAY",  "Workday Inc."),
    ("VEEV",  "Veeva Systems Inc."),
    ("ANET",  "Arista Networks Inc."),
    ("NXPI",  "NXP Semiconductors NV"),
    ("MCHP",  "Microchip Technology Inc."),
    ("ON",    "ON Semiconductor Corp."),
    ("STX",   "Seagate Technology Holdings"),
    ("WDC",   "Western Digital Corp."),
    ("NTAP",  "NetApp Inc."),
    ("ZBRA",  "Zebra Technologies Corp."),
    ("EPAM",  "EPAM Systems Inc."),
    ("TTWO",  "Take-Two Interactive Software"),
    ("EA",    "Electronic Arts Inc."),
    ("RBLX",  "Roblox Corp."),
    ("U",     "Unity Software Inc."),
    ("UBER",  "Uber Technologies Inc."),
    ("LYFT",  "Lyft Inc."),
    ("ABNB",  "Airbnb Inc."),
    ("DASH",  "DoorDash Inc."),
    ("EXPE",  "Expedia Group Inc."),
    ("BKNG",  "Booking Holdings Inc."),

    # ── Communication Services ──────────────────────────────────────────────────
    ("DIS",   "The Walt Disney Co."),
    ("CMCSA", "Comcast Corp."),
    ("T",     "AT&T Inc."),
    ("VZ",    "Verizon Communications Inc."),
    ("TMUS",  "T-Mobile US Inc."),
    ("CHTR",  "Charter Communications Inc."),
    ("WBD",   "Warner Bros. Discovery Inc."),
    ("PARA",  "Paramount Global"),
    ("SPOT",  "Spotify Technology SA"),
    ("SNAP",  "Snap Inc."),
    ("PINS",  "Pinterest Inc."),
    ("MTCH",  "Match Group Inc."),
    ("ZM",    "Zoom Video Communications"),

    # ── Consumer Discretionary ─────────────────────────────────────────────────
    ("HD",    "The Home Depot Inc."),
    ("MCD",   "McDonald's Corp."),
    ("NKE",   "Nike Inc."),
    ("SBUX",  "Starbucks Corp."),
    ("LOW",   "Lowe's Companies Inc."),
    ("TGT",   "Target Corp."),
    ("ROST",  "Ross Stores Inc."),
    ("TJX",   "TJX Companies Inc."),
    ("BURL",  "Burlington Stores Inc."),
    ("ULTA",  "Ulta Beauty Inc."),
    ("LULU",  "Lululemon Athletica Inc."),
    ("BBY",   "Best Buy Co. Inc."),
    ("DG",    "Dollar General Corp."),
    ("DLTR",  "Dollar Tree Inc."),
    ("ORLY",  "O'Reilly Automotive Inc."),
    ("AZO",   "AutoZone Inc."),
    ("AAP",   "Advance Auto Parts Inc."),
    ("GM",    "General Motors Co."),
    ("F",     "Ford Motor Co."),
    ("RIVN",  "Rivian Automotive Inc."),
    ("LCID",  "Lucid Group Inc."),
    ("MGM",   "MGM Resorts International"),
    ("LVS",   "Las Vegas Sands Corp."),
    ("WYNN",  "Wynn Resorts Ltd."),
    ("NCLH",  "Norwegian Cruise Line Holdings"),
    ("CCL",   "Carnival Corp."),
    ("RCL",   "Royal Caribbean Cruises Ltd."),
    ("HLT",   "Hilton Worldwide Holdings Inc."),
    ("MAR",   "Marriott International Inc."),
    ("H",     "Hyatt Hotels Corp."),
    ("AMZN",  "Amazon.com Inc."),
    ("ETSY",  "Etsy Inc."),
    ("EBAY",  "eBay Inc."),
    ("W",     "Wayfair Inc."),

    # ── Consumer Staples ───────────────────────────────────────────────────────
    ("PG",    "Procter & Gamble Co."),
    ("KO",    "The Coca-Cola Co."),
    ("PEP",   "PepsiCo Inc."),
    ("COST",  "Costco Wholesale Corp."),
    ("WMT",   "Walmart Inc."),
    ("PM",    "Philip Morris International Inc."),
    ("MO",    "Altria Group Inc."),
    ("CL",    "Colgate-Palmolive Co."),
    ("GIS",   "General Mills Inc."),
    ("K",     "Kellanova"),
    ("KHC",   "The Kraft Heinz Co."),
    ("MDLZ",  "Mondelez International Inc."),
    ("HSY",   "The Hershey Co."),
    ("CPB",   "Campbell Soup Co."),
    ("SJM",   "J.M. Smucker Co."),
    ("CLX",   "The Clorox Co."),
    ("CHD",   "Church & Dwight Co. Inc."),
    ("KMB",   "Kimberly-Clark Corp."),
    ("EL",    "Estée Lauder Companies Inc."),
    ("COTY",  "Coty Inc."),
    ("SYY",   "Sysco Corp."),
    ("KR",    "The Kroger Co."),
    ("WBA",   "Walgreens Boots Alliance Inc."),
    ("CVS",   "CVS Health Corp."),

    # ── Healthcare ─────────────────────────────────────────────────────────────
    ("JNJ",   "Johnson & Johnson"),
    ("UNH",   "UnitedHealth Group Inc."),
    ("LLY",   "Eli Lilly and Co."),
    ("MRK",   "Merck & Co. Inc."),
    ("ABBV",  "AbbVie Inc."),
    ("PFE",   "Pfizer Inc."),
    ("TMO",   "Thermo Fisher Scientific Inc."),
    ("ABT",   "Abbott Laboratories"),
    ("DHR",   "Danaher Corp."),
    ("BMY",   "Bristol-Myers Squibb Co."),
    ("AMGN",  "Amgen Inc."),
    ("GILD",  "Gilead Sciences Inc."),
    ("REGN",  "Regeneron Pharmaceuticals Inc."),
    ("VRTX",  "Vertex Pharmaceuticals Inc."),
    ("BIIB",  "Biogen Inc."),
    ("MRNA",  "Moderna Inc."),
    ("BNTX",  "BioNTech SE"),
    ("ISRG",  "Intuitive Surgical Inc."),
    ("SYK",   "Stryker Corp."),
    ("BSX",   "Boston Scientific Corp."),
    ("MDT",   "Medtronic plc"),
    ("EW",    "Edwards Lifesciences Corp."),
    ("ZBH",   "Zimmer Biomet Holdings Inc."),
    ("BDX",   "Becton Dickinson and Co."),
    ("IQV",   "IQVIA Holdings Inc."),
    ("CRL",   "Charles River Laboratories"),
    ("IDXX",  "IDEXX Laboratories Inc."),
    ("HCA",   "HCA Healthcare Inc."),
    ("HUM",   "Humana Inc."),
    ("CI",    "The Cigna Group"),
    ("ELV",   "Elevance Health Inc."),
    ("MCK",   "McKesson Corp."),
    ("CAH",   "Cardinal Health Inc."),
    ("COR",   "Cencora Inc."),
    ("DGX",   "Quest Diagnostics Inc."),
    ("LH",    "Labcorp"),

    # ── Financials ─────────────────────────────────────────────────────────────
    ("BRK-B", "Berkshire Hathaway Inc. (Class B)"),
    ("BRK-A", "Berkshire Hathaway Inc. (Class A)"),
    ("JPM",   "JPMorgan Chase & Co."),
    ("BAC",   "Bank of America Corp."),
    ("WFC",   "Wells Fargo & Co."),
    ("GS",    "The Goldman Sachs Group Inc."),
    ("MS",    "Morgan Stanley"),
    ("BLK",   "BlackRock Inc."),
    ("SCHW",  "Charles Schwab Corp."),
    ("AXP",   "American Express Co."),
    ("V",     "Visa Inc."),
    ("MA",    "Mastercard Inc."),
    ("PYPL",  "PayPal Holdings Inc."),
    ("SQ",    "Block Inc."),
    ("FI",    "Fiserv Inc."),
    ("FIS",   "Fidelity National Information Services"),
    ("GPN",   "Global Payments Inc."),
    ("C",     "Citigroup Inc."),
    ("USB",   "U.S. Bancorp"),
    ("PNC",   "PNC Financial Services Group Inc."),
    ("TFC",   "Truist Financial Corp."),
    ("COF",   "Capital One Financial Corp."),
    ("DFS",   "Discover Financial Services"),
    ("SYF",   "Synchrony Financial"),
    ("AIG",   "American International Group Inc."),
    ("MET",   "MetLife Inc."),
    ("PRU",   "Prudential Financial Inc."),
    ("AFL",   "Aflac Inc."),
    ("ALL",   "The Allstate Corp."),
    ("PGR",   "Progressive Corp."),
    ("TRV",   "The Travelers Companies Inc."),
    ("CB",    "Chubb Ltd."),
    ("MMC",   "Marsh & McLennan Companies Inc."),
    ("AON",   "Aon plc"),
    ("ICE",   "Intercontinental Exchange Inc."),
    ("CME",   "CME Group Inc."),
    ("MSCI",  "MSCI Inc."),
    ("SPGI",  "S&P Global Inc."),
    ("MCO",   "Moody's Corp."),
    ("IVZ",   "Invesco Ltd."),
    ("TROW",  "T. Rowe Price Group Inc."),
    ("BEN",   "Franklin Resources Inc."),
    ("NTRS",  "Northern Trust Corp."),
    ("STT",   "State Street Corp."),
    ("BK",    "Bank of New York Mellon Corp."),
    ("RF",    "Regions Financial Corp."),
    ("CFG",   "Citizens Financial Group Inc."),
    ("HBAN",  "Huntington Bancshares Inc."),
    ("KEY",   "KeyCorp"),
    ("FITB",  "Fifth Third Bancorp"),
    ("WRB",   "W.R. Berkley Corp."),

    # ── Energy ─────────────────────────────────────────────────────────────────
    ("XOM",   "Exxon Mobil Corp."),
    ("CVX",   "Chevron Corp."),
    ("COP",   "ConocoPhillips"),
    ("SLB",   "SLB (Schlumberger)"),
    ("EOG",   "EOG Resources Inc."),
    ("PXD",   "Pioneer Natural Resources Co."),
    ("MPC",   "Marathon Petroleum Corp."),
    ("VLO",   "Valero Energy Corp."),
    ("PSX",   "Phillips 66"),
    ("OXY",   "Occidental Petroleum Corp."),
    ("DVN",   "Devon Energy Corp."),
    ("FANG",  "Diamondback Energy Inc."),
    ("HES",   "Hess Corp."),
    ("KMI",   "Kinder Morgan Inc."),
    ("WMB",   "Williams Companies Inc."),
    ("OKE",   "ONEOK Inc."),
    ("LNG",   "Cheniere Energy Inc."),
    ("BKR",   "Baker Hughes Co."),
    ("HAL",   "Halliburton Co."),
    ("NOV",   "NOV Inc."),
    ("MRO",   "Marathon Oil Corp."),
    ("APA",   "APA Corp."),
    ("XLE",   "Energy Select Sector SPDR Fund"),

    # ── Industrials ────────────────────────────────────────────────────────────
    ("GE",    "GE Aerospace"),
    ("HON",   "Honeywell International Inc."),
    ("UNP",   "Union Pacific Corp."),
    ("UPS",   "United Parcel Service Inc."),
    ("BA",    "The Boeing Co."),
    ("CAT",   "Caterpillar Inc."),
    ("DE",    "Deere & Co."),
    ("MMM",   "3M Co."),
    ("LMT",   "Lockheed Martin Corp."),
    ("RTX",   "RTX Corp."),
    ("NOC",   "Northrop Grumman Corp."),
    ("GD",    "General Dynamics Corp."),
    ("HII",   "Huntington Ingalls Industries"),
    ("L3H",   "L3Harris Technologies Inc."),
    ("FDX",   "FedEx Corp."),
    ("NSC",   "Norfolk Southern Corp."),
    ("CSX",   "CSX Corp."),
    ("CP",    "Canadian Pacific Kansas City"),
    ("CNI",   "Canadian National Railway Co."),
    ("DAL",   "Delta Air Lines Inc."),
    ("UAL",   "United Airlines Holdings Inc."),
    ("AAL",   "American Airlines Group Inc."),
    ("LUV",   "Southwest Airlines Co."),
    ("ALK",   "Alaska Air Group Inc."),
    ("JBLU",  "JetBlue Airways Corp."),
    ("ETN",   "Eaton Corp. plc"),
    ("EMR",   "Emerson Electric Co."),
    ("ROK",   "Rockwell Automation Inc."),
    ("PH",    "Parker-Hannifin Corp."),
    ("IR",    "Ingersoll Rand Inc."),
    ("AME",   "AMETEK Inc."),
    ("XYL",   "Xylem Inc."),
    ("IEX",   "IDEX Corp."),
    ("GWW",   "W.W. Grainger Inc."),
    ("FAST",  "Fastenal Co."),
    ("CNHI",  "CNH Industrial NV"),
    ("PCAR",  "PACCAR Inc."),
    ("OSK",   "Oshkosh Corp."),
    ("TT",    "Trane Technologies plc"),
    ("CARR",  "Carrier Global Corp."),
    ("OTIS",  "Otis Worldwide Corp."),
    ("RSG",   "Republic Services Inc."),
    ("WM",    "Waste Management Inc."),

    # ── Materials ──────────────────────────────────────────────────────────────
    ("LIN",   "Linde plc"),
    ("APD",   "Air Products and Chemicals Inc."),
    ("SHW",   "Sherwin-Williams Co."),
    ("ECL",   "Ecolab Inc."),
    ("NEM",   "Newmont Corp."),
    ("FCX",   "Freeport-McMoRan Inc."),
    ("NUE",   "Nucor Corp."),
    ("STLD",  "Steel Dynamics Inc."),
    ("PKG",   "Packaging Corp. of America"),
    ("IP",    "International Paper Co."),
    ("CF",    "CF Industries Holdings Inc."),
    ("MOS",   "The Mosaic Co."),
    ("DOW",   "Dow Inc."),
    ("LYB",   "LyondellBasell Industries NV"),
    ("PPG",   "PPG Industries Inc."),
    ("ALB",   "Albemarle Corp."),
    ("CE",    "Celanese Corp."),

    # ── Real Estate ────────────────────────────────────────────────────────────
    ("PLD",   "Prologis Inc."),
    ("AMT",   "American Tower Corp."),
    ("EQIX",  "Equinix Inc."),
    ("SPG",   "Simon Property Group Inc."),
    ("CCI",   "Crown Castle Inc."),
    ("SBAC",  "SBA Communications Corp."),
    ("DLR",   "Digital Realty Trust Inc."),
    ("PSA",   "Public Storage"),
    ("EXR",   "Extra Space Storage Inc."),
    ("WELL",  "Welltower Inc."),
    ("VTR",   "Ventas Inc."),
    ("ARE",   "Alexandria Real Estate Equities"),
    ("BXP",   "BXP Inc."),
    ("SLG",   "SL Green Realty Corp."),
    ("O",     "Realty Income Corp."),
    ("VICI",  "VICI Properties Inc."),
    ("MAA",   "Mid-America Apartment Communities"),
    ("EQR",   "Equity Residential"),
    ("AVB",   "AvalonBay Communities Inc."),
    ("ESS",   "Essex Property Trust Inc."),

    # ── Utilities ──────────────────────────────────────────────────────────────
    ("NEE",   "NextEra Energy Inc."),
    ("DUK",   "Duke Energy Corp."),
    ("SO",    "The Southern Co."),
    ("D",     "Dominion Energy Inc."),
    ("SRE",   "Sempra"),
    ("AEP",   "American Electric Power Co."),
    ("XEL",   "Xcel Energy Inc."),
    ("PCG",   "PG&E Corp."),
    ("EIX",   "Edison International"),
    ("ED",    "Consolidated Edison Inc."),
    ("WEC",   "WEC Energy Group Inc."),
    ("ES",    "Eversource Energy"),
    ("ETR",   "Entergy Corp."),
    ("PPL",   "PPL Corp."),
    ("CNP",   "CenterPoint Energy Inc."),
    ("ATO",   "Atmos Energy Corp."),
    ("AWK",   "American Water Works Co. Inc."),

    # ── Popular ETFs ───────────────────────────────────────────────────────────
    ("SPY",   "SPDR S&P 500 ETF Trust"),
    ("IVV",   "iShares Core S&P 500 ETF"),
    ("QQQ",   "Invesco QQQ Trust (NASDAQ-100)"),
    ("IWM",   "iShares Russell 2000 ETF"),
    ("DIA",   "SPDR Dow Jones Industrial ETF"),
    ("VTI",   "Vanguard Total Stock Market ETF"),
    ("VOO",   "Vanguard S&P 500 ETF"),
    ("VEA",   "Vanguard FTSE Developed Markets ETF"),
    ("VWO",   "Vanguard FTSE Emerging Markets ETF"),
    ("EFA",   "iShares MSCI EAFE ETF"),
    ("EEM",   "iShares MSCI Emerging Markets ETF"),
    ("GLD",   "SPDR Gold Shares"),
    ("SLV",   "iShares Silver Trust"),
    ("USO",   "United States Oil Fund"),
    ("UNG",   "United States Natural Gas Fund"),
    ("XLF",   "Financial Select Sector SPDR"),
    ("XLK",   "Technology Select Sector SPDR"),
    ("XLE",   "Energy Select Sector SPDR"),
    ("XLV",   "Health Care Select Sector SPDR"),
    ("XLI",   "Industrial Select Sector SPDR"),
    ("XLY",   "Consumer Discret. Select Sector SPDR"),
    ("XLP",   "Consumer Staples Select Sector SPDR"),
    ("XLU",   "Utilities Select Sector SPDR"),
    ("XLRE",  "Real Estate Select Sector SPDR"),
    ("XLC",   "Communication Services Select Sector SPDR"),
    ("XLB",   "Materials Select Sector SPDR"),
    ("VNQ",   "Vanguard Real Estate ETF"),
    ("AGG",   "iShares Core U.S. Aggregate Bond ETF"),
    ("BND",   "Vanguard Total Bond Market ETF"),
    ("TLT",   "iShares 20+ Year Treasury Bond ETF"),
    ("IEF",   "iShares 7-10 Year Treasury Bond ETF"),
    ("HYG",   "iShares iBoxx High Yield Corp Bond ETF"),
    ("LQD",   "iShares iBoxx Investment Grade Corp Bond ETF"),
    ("ARKK",  "ARK Innovation ETF"),
    ("ARKG",  "ARK Genomic Revolution ETF"),
    ("SOXX",  "iShares Semiconductor ETF"),
    ("SMH",   "VanEck Semiconductor ETF"),
    ("KWEB",  "KraneShares CSI China Internet ETF"),
    ("MCHI",  "iShares MSCI China ETF"),
    ("EWJ",   "iShares MSCI Japan ETF"),
    ("EWZ",   "iShares MSCI Brazil ETF"),
    ("GDX",   "VanEck Gold Miners ETF"),
    ("GDXJ",  "VanEck Junior Gold Miners ETF"),
    ("SOXL",  "Direxion Daily Semi Bull 3X ETF"),
    ("TQQQ",  "ProShares UltraPro QQQ"),
    ("SPXL",  "Direxion Daily S&P 500 Bull 3X ETF"),
]

# Deduplicate (same ticker may appear in multiple sectors)
_seen: set[str] = set()
_unique: list[tuple[str, str]] = []
for sym, name in _TICKERS:
    if sym not in _seen:
        _seen.add(sym)
        _unique.append((sym, name))

# Dash Dropdown options format
TICKER_OPTIONS: list[dict] = [
    {"value": sym, "label": f"{sym}  —  {name}"}
    for sym, name in sorted(_unique, key=lambda x: x[0])
]
